# Generated by Django 3.2.5 on 2021-07-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_method', models.CharField(max_length=120, verbose_name='Метод контроля')),
            ],
            options={
                'verbose_name': 'Метод контроля',
                'verbose_name_plural': 'Методы контроля',
            },
        ),
        migrations.CreateModel(
            name='ControlStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_stage', models.CharField(max_length=120, verbose_name='Стадия контроля')),
            ],
            options={
                'verbose_name': 'Стадия контроля',
                'verbose_name_plural': 'Стадии контроля',
            },
        ),
        migrations.CreateModel(
            name='ScopeOfControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_control', models.CharField(max_length=120, verbose_name='Объем контроля')),
            ],
            options={
                'verbose_name': 'Объем контроля',
                'verbose_name_plural': 'Объем контроля',
            },
        ),
        migrations.CreateModel(
            name='WorkGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_group', models.CharField(blank=True, max_length=150, verbose_name='Группа работ')),
            ],
            options={
                'verbose_name': 'Группа работ',
                'verbose_name_plural': 'Группы работ',
            },
        ),
        migrations.CreateModel(
            name='WorkTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(blank=True, max_length=150, verbose_name='Вид работ')),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.workgroups', verbose_name='Группа работ')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='ControlTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер по порядку')),
                ('control_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.controlmethod')),
                ('control_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.controlstage')),
                ('scope_of_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.scopeofcontrol')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.worktypes')),
            ],
            options={
                'verbose_name': 'Номер по порядку',
                'verbose_name_plural': 'Номера по порядку',
            },
        ),
    ]
