# Generated by Django 3.2.5 on 2021-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_controlmethod_controlstage_controltypes_scopeofcontrol_workgroups_worktypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktypes',
            name='control_method',
            field=models.ManyToManyField(through='mm.ControlTypes', to='mm.ControlMethod'),
        ),
        migrations.AddField(
            model_name='worktypes',
            name='control_stage',
            field=models.ManyToManyField(through='mm.ControlTypes', to='mm.ControlStage'),
        ),
        migrations.AddField(
            model_name='worktypes',
            name='scope_of_control',
            field=models.ManyToManyField(through='mm.ControlTypes', to='mm.ScopeOfControl'),
        ),
    ]
