# Generated by Django 3.2.5 on 2021-08-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20210729_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controltypes',
            old_name='number',
            new_name='order',
        ),
    ]
